### ISSUE TITLE
Requires Fabric API

### ISSUE THREAD

**Issue by Niterux** [sakura-ryoko/afkplus#12]
This mod requires Fabric API but it isn't stated on the mods page.
![image](https://github.com/sakura-ryoko/afkplus/assets/110568869/7c4ec503-d416-44b0-99fe-169b565c4d0f)
![image](https://github.com/sakura-ryoko/afkplus/assets/110568869/367b991e-52b2-4a59-9d5b-7c7df9e27b80)

**Comment by sakura-ryoko** [comment]
Fabric Loader is listed under the basic metadata, where for 1.20.2 uses between fabric 0.89 through 0.91.  You can upgrade your Fabric API, which should be obvious.

https://modrinth.com/mod/fabric-api/versions?g=1.20.2

**Comment by Niterux** [comment]
Thank you for adding Fabric API dependency to Modrinth
