### ISSUE TITLE
Is there a way to disable damage while being AFK?

### ISSUE THREAD

**Issue by ryu0q** [sakura-ryoko/afkplus#17]
**Is your feature request related to a problem? Please describe.**
This mod is the only updated and proper one I could find for fabric, but it lacks the feature of disabling damage to AFK players. I understand that this mod's reason may solely be to tell other players when someone is AFK.

**Describe the solution you'd like**
A functionality which disables the damage given to the AFK player.

**Describe alternatives you've considered**
A separate mod that uses the placeholders to give the player temporary invincibility for the time the player is AFK.

**Comment by sakura-ryoko** [comment]
This is an item on my TO DO list.  I believe there is an older mod that performs a similar function, am I right ?

**Comment by sakura-ryoko** [comment]
Check out version 1.4.1 of the 1.20.x branches.
