### ISSUE TITLE
Two feature ideas

### ISSUE THREAD

**Issue by sternschnaube** [sakura-ryoko/afkplus#20]
## 2. New command like /noafk, which prevents to turn the player into auto-AFK mode.
Optional with custom tag next to the player name, as it is with AFK.

**Comment by sakura-ryoko** [comment]
the /noafk is more interesting, but the "no phantom spawning" would be a bit more complicated.

**Comment by sakura-ryoko** [comment]
And I'll get to this later; because I am currently hard at work on malilib & masa's other mods for the new snapshot's networking code.

**Comment by sternschnaube** [comment]
Thanks for informing me, you got all the time 😄 
------------

![image](https://github.com/sakura-ryoko/afkplus/assets/120551916/9f360526-0fa2-4b61-9316-239dc215dd41)
When I use the /afk command, it shows 4 messages, the first two irritates me a bit. 
Maybe you could remove that? I have OP rights, if that's matters.

**Comment by sakura-ryoko** [comment]
In regards to your image, if you want to cut down on the messages you can disable features via your config, ie "resetOnMovement", or if you want to disable the "Invulnerable" announcers, set them to "" .

**Comment by sakura-ryoko** [comment]
Check out the 1.4.6 release.

**Comment by sakura-ryoko** [comment]
Let me know if there are additional issues.

**Comment by sternschnaube** [comment]
Thanks for the detailed answer. Resetting the config was a good idea. 

It's nice that you were able to add the phantom rule, 
it is said to have happened that I stood AFK a little longer and was very surprised 😂😂😂

![2024-01-20_01 57 21](https://github.com/sakura-ryoko/afkplus/assets/120551916/72b1f42c-cf4e-4d0c-833e-2343b775aea6)

Your mod is super helpful - big THANKS! 😊
