### ISSUE TITLE
[Feature] Don't consider AFK players for sleep percentage

### ISSUE THREAD

**Issue by LittleCircleOO** [sakura-ryoko/afkplus#21]
I think the AFK state would be a bit more practical if players in the AFK state were not counted in the player sleep percentage. This would be useful for servers with players who are AFK for long periods of time.

Refer to the implementation of this feature in [essential commands](https://github.com/John-Paul-R/Essential-Commands/commit/fbeeda23460bec0a7015bab025ceb83d2e6a113d)

**Comment by sakura-ryoko** [comment]
Yes this is a feature on my TODO list.

**Comment by sakura-ryoko** [comment]
Check out the 1.4.6 release.

**Comment by LittleCircleOO** [comment]
it works, thanks
