### ISSUE TITLE
Option to configure the (Gone for: xxxx) Message

### ISSUE THREAD

**Issue by tr1m1n4t0r** [sakura-ryoko/afkplus#29]
I think it would be pretty nice to be able to change the text for the message for how long a player was afk.
So maybe a option under [messageOptions] in the afkplus.toml could be possible?

Example
For me i would like to change (Gone for: xxxx) to (Abwesend für: xxxx).

Maybe it could then look something like this in the .toml
displayDuration = true
displayDurationFormat = " <gray>(Gone for: %afkplus:duration%)<r>"

Edit:
In the same way a option for renaming the afk reason (for example timeout) would be more than great for me

**Comment by sakura-ryoko** [comment]
The config will be slightly different; because the way the mod works, is the Time/Date and Duration handling are configured separately between the placeholders and the Message / AfkInfo fields; so in order to accomplish this and in an attempt to make the Duration and Time/Date formatting configurable; it made it a selection of multiple options; and each has an optional "format" option, with a configurable `format` string.

This is a complicated topic to describe; but the changes I have pending do make this a bit easier code-wise; once you have it all configured.

So, the JSON (No longer TOML, I need to update the README) would look something like this:
```json
"place_holder": {
    "afkPlaceholder": "<i><gray>[AFK%afkplus:invulnerable%]<r>",
    "afkPlusNamePlaceholderAfk": "<i><gray>[AFK%afkplus:invulnerable%] %player:displayname_unformatted%<r>",
    "afkPlusNamePlaceholder": "%player:displayname%",
    "afkDurationPlaceholderFormatting": "<green>",
    "afkTimePlaceholderFormatting": "<green>",
    "afkReasonPlaceholderFormatting": "",
    "afkInvulnerablePlaceholder": ":<red>I<r>",
    "duration": {
      "option": "REGULAR",
      "customFormat": ""
    },
    "timeDate": {
      "option": "REGULAR",
      "customFormat": ""
    }
  },
  "message": {
    "enableMessages": true,
    "whenAfk": "%player:displayname% <yellow>is now AFK<r>",
    "whenAfkPunctuation": "<yellow>,<r> ",
    "whenReturn": "%player:displayname% <yellow>is no longer AFK<r>",
    "whenReturnDurationPrefix": " <gray>(Gone for: <green>",
    "whenReturnDurationSuffix": "<gray>)",
    "defaultReason": "<gray>poof!<r>",
    "whenDamageDisabled": "%player:displayname% <yellow>is marked as <red>Invulnerable.<r>",
    "whenDamageEnabled": "%player:displayname% <yellow>is no longer <red>Invulnerable.<r>",
    "displayDuration": true,
    "afkKickMessage": "<copper>AFK beyond the allowed time limit set by your Administrator.<r>",
    "whenKicked": "%player:displayname% <copper>was kicked for being AFK.<r>",
    "whenKickedDefaultReason": "<copper>AFK timeout",
    "whenKickedDurationDefaultPrefix": " <gray>(Gone for: <green>",
    "whenKickedDurationNamedPrefix": " <gray>(%player:displayname% was gone for: <green>",
    "whenKickedDurationSuffix": "<gray>)",
    "duration": {
      "option": "PRETTY",
      "customFormat": ""
    },
    "timeDate": {
      "option": "REGULAR",
      "customFormat": ""
    }
  }
  ```

**Comment by sakura-ryoko** [comment]
Where they "pretty" "regular" "formatted", etc are all configurable options such as:

```
*** Duration Test:\n
Random Value: 1248857273\n
REGULAR: (346:54:17.273) // [Format: HH:mm:ss.SSS]\n
PRETTY: (14 days 10 hours 54 minutes 17 seconds) // [Format: d' days 'H' hours 'm' minutes 's' seconds']\n
FORMATTED: (346:54:17.273) // [Format: HH:mm:ss.SSS]\n
Done\n
*** Time/Date Test:\n
Vanilla Formatted Now: 2024-12-26_18.45.13\n
REGULAR: (2024-12-26_18.45.13) // [Format: yyyy-MM-dd_HH.mm.ss]\n
SIMPLE: (2024-12-26T18:45:13.2391518) // [Format: yyyy-MM-ddTHH:mm:ss.n]\n
FORMATTED: (2024-12-26_18.45.13) // [Format: yyyy-MM-dd_HH.mm.ss]\n
RFC1123: (Thu, 26 Dec 2024 18:45:13 -0500) // [Format: EEE, dd MMM yyyy HH:mm:ss +HHMM]\n
Done\n
```

Where using the `formatted` configuration; you can manually specify a Java TimeDateFormatter Pattern such as:
`yyyy-MM-dd_HH.mm.ss` in your JSON config.

Of note as well, the `TimeFormat.SIMPLE` option, doesn't look too simple.  It's the 'ISO_LOCAL_DATE_TIME` config.

**Comment by sakura-ryoko** [comment]
But with all of these advanced options; this makes the `Gone for XXX` display to be fully configurable.  Eventually I do hope to "tidy up" the Config Options from the current structure a bit to make it a bit more Coherent.
