### ISSUE TITLE
Using /afk when already AFK should only remove AFK status

### ISSUE THREAD

**Issue by szernex** [sakura-ryoko/afkplus#30]
**Is your feature request related to a problem? Please describe.**
When a player is marked as AFK, be it from inactivity or by manually using the /afk command, it would only make sense in my opinion to be able to use just the /afk command again to no longer be marked as AFK. Right now it will first no longer mark you as AFK and then immediately mark you as AFK again, so the only way to return is to left or right click when resetOnMovement and resetOnLook are set to false.

https://github.com/user-attachments/assets/18cff6a0-c32e-4c1d-a28a-a191090f586f

**Describe the solution you'd like**
My ideal solution would be:
Player uses `/afk [optional reason]` to mark themselves as AFK.
Once they return they can use just `/afk` to no longer mark themselves as AFK.

**Describe alternatives you've considered**
Setting resetOnMovement to true would somewhat work around that, except that it also gets triggered when the player gets moved by someone or something else, which kind of defeats the purpose of being marked as AFK when other players can un-mark you.

**Comment by sakura-ryoko** [comment]
I've added this to the Multi Version code of the mod, thus far.

**Comment by sakura-ryoko** [comment]
I need to just re-confirm that the code is working as expected for this, or not.

**Comment by sakura-ryoko** [comment]
I've added an "afk cooldown" with a short default delay, and related message that inhibits this, as reported.

**Comment by toydotgame** [comment]
(Recently updated from 1.21 to 1.21.8 and thus new AFKPlus version)
I see that using `/afk` to un-AFK has changed (now with a cooldown to prevent the issue described here), but I have noticed that, unlike some other message options, setting `afkCooldownGreeting` to an empty string does **not** disable the message from printing. Is there any chance this ability can be added to disable the message (either by a boolean toggle or by empty string) \[\[literally saving like a single line of chat that in _my opinion_ is redundant given the user knows they did `/afk` to un-AFK\]\].
