### ISSUE TITLE
[Request] Compatibility with DrexHD's Vanish

### ISSUE THREAD

**Issue by Zeklandia** [sakura-ryoko/afkplus#32]
**Is your feature request related to a problem? Please describe.**
When a server staff member has used `/vanish`, they are still subject to AfkPlus' automatic state changes (e.g., time-based setting of AFK status, movement-based clearing of AFK status). This reveals a vanished staff member to still be connected to the server.

**Describe the solution you'd like**
AfkPlus should ignore vanished players.

**Describe alternatives you've considered**
*N/A*

**Additional context**
*N/A*

**Comment by sakura-ryoko** [comment]
This was added to my Multi Version branch.  The Vanish Mod support is new, and only partially tested.  I plan on adding more Event hooks for it in the future.
