### ISSUE TITLE
AFK Status Removed by Hits or Pushes, Making Players Vulnerable

### ISSUE THREAD

**Issue by SniperOwl** [sakura-ryoko/afkplus#34]
### Bug description

When a player is marked as AFK using the afkplus mod, their AFK status can be removed under two scenarios:

If another player hits the AFK player, the AFK status is removed, even if disableDamage is enabled.
If an entity (e.g., a mob) pushes the AFK player, the AFK status is also removed.
This behavior leaves AFK players vulnerable to attacks or environmental hazards, undermining the protection provided by the disableDamage option. From the available configuration options, there doesn't appear to be a way to prevent AFK status removal in these cases.

### Steps to reproduce

1. Enable the disableDamage option.
2. Have a player enter AFK status.
3. Hit the AFK player or push them with an entity.
4. Observe that the AFK status is removed, and the player becomes vulnerable.

### Expected behavior

The AFK status should not be removed when:

1. Another player hits the AFK player (the hit should be ignored entirely).
2. An entity (e.g., a mob) collides with the AFK player, causing them to move (entity collision should be disabled while the player is invulnerable).

### Actual behavior

The AFK status is removed, leaving the player vulnerable to further attacks or hazards.

### Minecraft version

1.21.4

### TemplateMod version

1.5.3

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by sakura-ryoko** [comment]
This is primarily due to whenever a player is "moved or pushed" Vanilla updates the player's LastActionTime, which in turn is configured to disable AFK Status.

**Comment by sakura-ryoko** [comment]
It's a thing where addressing some of these issues is part of my Mod Refactor project which has only just begun.

**Comment by sakura-ryoko** [comment]
I've added this to my current Multiversion tree.  The mod now causes `DisableDamage` players not not be able to be pushed by other Mobs / Entities.  The behavior is the same as if you are trying to "Push" a Wither or Warden; and the game just kind of just pushes back on you encroaching into their Hit Box.
