### ISSUE TITLE
Thank you for the Fork!

### ISSUE THREAD

**Issue by beabfc** [sakura-ryoko/afkplus#5]
I'm the author of the original project ([beabfc/afkdisplay](https://github.com/beabfc/afkdisplay)) which this is mod based on.

I wrote the mod for a private server because I didn't like the other AFK mods on modrinth and figured I should publish it to help others. Unfortunately I do not have the time to maintain the mod and keep it up to date. I'm really busy at the moment and don't play as much Minecraft anymore. I never expected anyone else to take interest in this 'simple' project of mine.

Thank you for all the contributions and the PRs you created in my repo. I always saw the notifications pop up in my mail account but never really had the time to logon to GitHub. I'm really sorry! I saw how much work you put into improving the mod and I really appreciate it!

I just looked at a few of the changes you implemented and am really happy. If it's okay with you I'm would like to archive my repository and recommend this fork in the readme instead.

Kind Regards

**Comment by sakura-ryoko** [comment]
Awesome, thank you for responding!

**Comment by ghost** [comment]
Thank you all for your contuined work on this project. My originally very simple mod has evolved into a very sophisticated and complicated solution for all kinds of usecases. While the complexity is not part of original vision of mininalism I'm still very happy to see my small project has lived on and grown. I will now retire this _(secondary)_ GitHub account. As such you don't have to credit me as the original author anymore if you don't want to. I think this codebase can be compared to theseus' ship. My original work has probably been completly replaced by newer, better code.

Thanks! beabfc out.
